/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Text Input Context
 #	author : miyako
 #	2019/06/27
 #
 # --------------------------------------------------------------------------------*/



// --- Text Input Context
void INPUT_SOURCES_LIST(PA_PluginParameters params);
void Get_input_source(PA_PluginParameters params);
void SET_INPUT_SOURCE(PA_PluginParameters params);
void GET_INPUT_SOURCE_LOCALES(PA_PluginParameters params);
void SET_INPUT_SOURCE_LOCALES(PA_PluginParameters params);

void CommandDispatcherInMainProcess (int32_t pProcNum, PA_PluginParameters params);
