/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Text Input Context
 #	author : miyako
 #	2019/06/27
 #
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TEXT_INPUT_CONTEXT_H
#define PLUGIN_TEXT_INPUT_CONTEXT_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "ARRAY_TEXT.h"

// --- Text Input Context
void _o_INPUT_SOURCES_LIST(PA_PluginParameters params);
void _o_Get_input_source(PA_PluginParameters params);
void SET_INPUT_SOURCE(PA_PluginParameters params);
void GET_INPUT_SOURCE_LOCALES(PA_PluginParameters params);
void SET_INPUT_SOURCE_LOCALES(PA_PluginParameters params);
void INPUT_SOURCES_LIST(PA_PluginParameters params);
void Get_input_source(PA_PluginParameters params);

void CommandDispatcherInMainProcess (PA_long32 selector, PA_PluginParameters params);

#include "4DPlugin-JSON.h"

#endif /* PLUGIN_TEXT_INPUT_CONTEXT_H */
